### ISSUE TITLE
Unable to Debug Custom Kong plugin inside Docker container

### ISSUE THREAD

**Issue by cotnic** [EmmyLua/EmmyLuaDebugger#47]
I am attempting to enable remote debugging of my custom Kong plugin, which is developed in Lua language inside the Pongo framework. To achieve this, I've integrated the EmyLuaDebugger plugin for IntelliJ IDEA and added the necessary debug code inside my Lua script. Additionally, I have exposed the ports for remote debugging from within the Docker container and included the emmy_core.so file inside the container.

However, I am encountering an issue where the debugger successfully connects but then immediately disconnects. Consequently, the breakpoint is not triggered, and I am unable to debug the code effectively. I discovered in a blog post that this behavior might be due to the path not being correctly resolved inside the Docker container.

_Expected Behavior_:
The debugger should connect successfully, stop at the breakpoints set in the Lua code, and allow for effective debugging of the custom Kong plugin.

_Actual Behavior:_
The debugger connects but immediately disconnects, and breakpoints are not triggered.

**Additional Information**:

* I have followed the blog post [Debugging Lua](https://devpress.csdn.net/cloudnative/62f395cec6770329307f8912.html) and learned that the fixPath function might be necessary to handle path mapping inside the Docker container.
* I attempted to implement the fixPath function, but I am unsure about the correct way to do it for my specific Docker setup.
* I am using the EmyLuaDebugger plugin with IntelliJ IDEA for remote debugging.

Any assistance in resolving this issue and properly setting up the fixPath function would be greatly appreciated.

cc: @CppCXY

**Comment by CppCXY** [comment]
If the connection is disconnected, it may be due to your process crashing. 
You can check the following points: 
1. ensure that there is only one worker process, insert the debug code during the initialization stage of the worker process instead of the master process.
2. Did the process actually crash? Is there any log available?
3. If EmmyLua is not working properly, it is recommended to use the lua-debug plugin for VSCode. There are dedicated maintainers for debugging OpenResty-related issues. However, I can assure you that EmmyLua can debug frameworks based on OpenResty. You may consider downloading the latest version from the releases page as the debugger in IntelliJ is several months behind.
